application: puddlejumpersworkshop-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "1d"

handlers:
- url: /img
  static_dir: img
- url: /common
  static_dir: common
- url: /
  static_files: index.html
  upload: index.html
- url: /accept-ipn
  script: accept_paypal_ipn.app
- url: /get-payments
  script: dump_ipns.app
- url: /dump-ipns
  script: dump_ipns.app
- url: /dump-ipn
  script: dump_ipn.app
- url: /([A-Za-z0-9\-]*.html)
  static_files: \1
  upload: dummy|[\w\-]*.html

libraries:
- name: webapp2
  version: "2.5.1"
- name: django
  version: "1.2"
