application: puddlejumpersworkshop-hrd
version: 1
runtime: python
api_version: 1
default_expiration: "1d"
handlers:
- url: /img
  static_dir: img
- url: /common
  static_dir: common
- url: /
  static_files: index.html
  upload: index.html
- url: /accept-ipn
  script: accept-paypal-ipn.py
- url: /get-payments
  script: dump-ipns.py
- url: /dump-ipn
  script: dump-ipn.py
- url: /[A-Za-z0-9\-]*.html
  static_files: \1.html
  upload: dummy|[\w\-]*.html
