application: puddlejumpersworkshop
version: 1
runtime: python
api_version: 1
default_expiration: "1d"
handlers:
- url: /img
  static_dir: img
- url: /common
  static_dir: common
- url: /
  static_files: index.html
  upload: index.html
- url: /(.*).html
  static_files: \1.html
  upload: .*.html
